# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef759a7d643cf9a0eff0497c533d89dd04ebafcc166e960bc0d15f18a4387305a456dfbc52a09686943b3b832941e7ba8e38743d2958f6d66db9a3d70b909d43

test:
  secret_key_base: 914e923277e59c1cf0b33e279b668522de1f9bfe001f1c5505d441f517a8ccb90e4d218ba2e24e8f4d9694129c6579cbc6e3848399854dc7f6e9df33e1dad8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
